### ISSUE TITLE
Heading line height in editing should be as same as the one in reading

### ISSUE THREAD

**Issue by johnson86tw** [chnejohnson/obsidian-nerd#11]
- The left hand side is in editing and the right hand side is in reading

![Image](https://user-images.githubusercontent.com/31992185/211247685-9c77a79e-cedd-4b92-9d4b-ba73a08f53e2.png)

**Comment by johnson86tw** [comment]
Use `--h3-line-height` to adjust the line height in editing

 ```css
.theme-dark {
	--h1-line-height: 60px;
	--h2-line-height: 60px;
	--h3-line-height: 60px;
	--h4-line-height: 60px;
	--h5-line-height: 60px;
	--h6-line-height: 60px;
	--h3-line-height: 60px;
}
```

**Comment by johnson86tw** [comment]
This is the right one

```css
.HyperMD-header {
	padding-top: 20px !important;
	padding-bottom: 25px !important;
}
```
