### ISSUE TITLE
Let bullet indention length in editing be as same as the one in reading 😖

### ISSUE THREAD

**Issue by johnson86tw** [chnejohnson/obsidian-nerd#3]
- the left hand side is in editing mode, and the right hand side is in reading mode

![截圖 2023-01-08 下午4 51 22](https://user-images.githubusercontent.com/31992185/211188065-c76e16fa-2936-44cd-a4a3-b58a14f28ac6.png)

**Comment by johnson86tw** [comment]
A temporary workaround, there're some problems with the cursor position and the next line indention...🥲



![Image](https://user-images.githubusercontent.com/31992185/212596556-e5eeafc6-3ec2-4b98-b282-afa1a8b9f548.png)


```css
span.cm-formatting-list {
	position: relative;
	left: -10px;
}
```
