### ISSUE TITLE
How to change bullet color?

### ISSUE THREAD

**Issue by johnson86tw** [chnejohnson/obsidian-nerd#8]
![Image](https://user-images.githubusercontent.com/31992185/211199542-ccf4ae10-78e0-4626-823c-5f54d5acc988.png)

**Comment by johnson86tw** [comment]
```css
body {
	--list-marker-color: var(--yellow);
	--list-marker-color-hover: var(--yellow);
}
```
